name: my_myntra
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  http: ^0.13.1
  mongo_dart: ^0.5.0+1
  google_fonts: ^2.0.0
  alan_voice: ^2.0.15
  geolocator: ^6.2.0
  provider: ^4.3.3
  google_maps_flutter:
  google_maps_webservice: ^0.0.19
  flutter_google_places: ^0.2.4
  flutter_polyline_points: ^0.2.1
  google_map_polyline:
  android_intent: ^2.0.0
  flutter_mapbox_navigation: ^0.0.19
  location:
  map_launcher: ^2.0.0
  flutter_svg: ^0.20.0-nullsafety.3
  rflutter_alert: ^2.0.2
  flutter_speed_dial: ^3.0.5
  auto_size_text: ^2.1.0
  qr_flutter: ^4.0.0
  barcode_scan_fix: ^1.0.2





dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

    # To add assets to your application, add an assets section, like this:
  assets:
    - assets/


  fonts:
    - family: Anton
      fonts:
        - asset: fonts/Anton-Regular.ttf
    - family: Teko
      fonts:
        - asset: fonts/Teko-Regular.ttf
    - family: Amiri
      fonts:
        - asset: fonts/Amiri-Regular.ttf
    - family: Amiri
      fonts:
        - asset: fonts/Amiri-Regular.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
